services:
  mysql:
    image: mysql:8.0
    container_name: nba_stats_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nba_stats
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # שינוי פורט חיצוני ל-3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: nba_stats_redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  mysql_data:
