POST http://localhost:8080/api/players/create/
Content-Type: application/json

{
  "name": "Player One",
  "idNumber": "123456744",
  "teamName": "Team Home",
  "gameStats": {
    "gameDate": "2025-03-07T20:00:00",
    "points": 28,
    "rebounds": 9,
    "assists": 5,
    "steals": 3,
    "blocks": 1,
    "fouls": 2,
    "turnovers": 4,
    "minutesPlayed": 2
  }
}
